apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-dev
  namespace: dev-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akhileshmishrabiz/April26-bootcamp.git
    targetRevision: argo-dev
    path: production-eks-env/multi-env-eks-stuff/eks-microservices/helm-services
    helm:
      releaseName: ecommerce-dev
      valueFiles:
        - ../environments/dev/value.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
